### ISSUE TITLE
Fix alembic migrations

### ISSUE THREAD

**Issue by aminalaee** [aminalaee/fastapi-storages#27]
When generating automatic alembic migrations, imports and storage argument are missing.

**Comment by mmzeynalli** [comment]
I believe there are two ways to fix it:
1. Add to documentation that user needs to add these paths to `script.py.mako` file manually to be able to use
2. User creates new "type", to avoid storage argument repitition and adds that path to `script.py.mako`. I have used this:

```
class File(FileType):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(storage=storage, *args, **kwargs)
```
And added path of this class to `script.py.mako`. Works like charm.

**Comment by mmzeynalli** [comment]
Appearantly, one cannot register a new type to alembic in any way. I am kinda dissapointed that this feature is missing. 

https://alembic.sqlalchemy.org/en/latest/autogenerate.html#controlling-the-module-prefix

You need always to manually add your types path to mako file

**Comment by aminalaee** [comment]
Hmm..yeah that makes sense. Feel free to add a section to the docs to explain this.
Thanks for taking a look into this :+1:

**Comment by aminalaee** [comment]
FIxed in https://github.com/aminalaee/fastapi-storages/pull/35
