### ISSUE TITLE
Not able to edit fields in sql admin when using s3 filetype

### ISSUE THREAD

**Issue by Shauryadhaka** [aminalaee/fastapi-storages#44]
Hey guys,
So i am not able to edit other fields when i saved a entry in my table with column being file type. It asks me to upload an image to save the model.

My model looks like this:
   `class PartnerDashboardPlaceholder1(Base):
    __tablename__ = "Carousel1"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    title = Column(String(255), nullable=True)
    subtitle = Column(String(255), nullable=True)
    image = Column(FileType(), nullable=True)
    # image_url = Column(String(255), nullable=True)
    read_more_link: Mapped[str] = mapped_column(String(), default=None, nullable=True)
    is_active: Mapped[bool] = mapped_column(Boolean(), default=False)
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())`
    

I get this error when i try to save it:

`
(builtins.AttributeError) 'NoneType' object has no attribute 'read' [SQL: UPDATE "Carousel1" SET title=$1::VARCHAR, subtitle=$2::VARCHAR, image=$3::VARCHAR, updated_at=$4::TIMESTAMP WITHOUT TIME ZONE WHERE "Carousel1".id = $5::INTEGER] [parameters: [{'image': <starlette.datastructures.UploadFile object at 0x7fb2383e9110>, 'title': 'Test data', 'subtitle': 'Test123123123', 'updated_at': datetime.datetime(2024, 1, 16, 11, 13, 55), 'Carousel1_id': 1}]]
`
![Capture](https://github.com/aminalaee/fastapi-storages/assets/10103234/371fb537-c262-447c-a70a-cef5fe33bb77)

Also the field doesn't shows anything even thou there is a file saved in the field. Can someone help if i am doing something wrong?

**Comment by ASTimch** [comment]
I've found that field doesn't shows filename (both for FileType and ImageType) even for FileSystemStorage (not only S3).

**Comment by Shauryadhaka** [comment]
Yeh the problem it forces me to upload a new file and I just want to change the content of some other field 😅

**Comment by Shauryadhaka** [comment]
@aminalaee is this an issue with the admin or fastapi-storage?

**Comment by aminalaee** [comment]
I need to check but I'm guessing it's SQLAdmin as it should check if there's already a value for this File/Image field, then it's not required to always upload a file.

**Comment by aminalaee** [comment]
Addressed in SQLAdmin.
