### ISSUE TITLE
Getting 502 Bad Gateway via using S3Storage(AWS_S3_USE_SSL)

### ISSUE THREAD

**Issue by logicli0n** [aminalaee/fastapi-storages#51]
When I'm editing or creating table with file.I'm getting 502 Bad Gateway.

**Comment by logicli0n** [comment]
![Uploading Screenshot 2024-08-19 at 8.00.04 PM.png…]()

**Comment by logicli0n** [comment]
<img width="1680" alt="Screenshot 2024-08-19 at 8 00 04 PM" src="https://github.com/user-attachments/assets/68df8451-1235-40b6-9271-8cddd3d9db87">

**Comment by logicli0n** [comment]
![Uploading Screenshot 2024-08-19 at 8.02.37 PM.png…]()

**Comment by logicli0n** [comment]
<img width="1680" alt="Screenshot 2024-08-19 at 8 02 37 PM" src="https://github.com/user-attachments/assets/ea3af0c5-bb93-453e-84d6-4dde84e4b51a">

**Comment by logicli0n** [comment]
![Uploading Screenshot 2024-08-19 at 8.00.38 PM.png…]()

**Comment by aminalaee** [comment]
Can you check the logs or console or somewhere? Without some traceback it's really hard to help

**Comment by logicli0n** [comment]
http://hb.bizmrg.com/cpd_test_backet/J0B1TvZsTKFXBqANX05d2WI0DOSJBRdrT6srGjal.jpeg
DEBUG {'uri': 'http://hb.bizmrg.com/cpd_test_backet/J0B1TvZsTKFXBqANX05d2WI0DOSJBRdrT6srGjal.jpeg', 'mode': 'rb', 'buffering': -1, 'encoding': None, 'errors': None, 'newline': None, 'closefd': True, 'opener': None, 'compression': 'infer_from_extension', 'transport_params': None} | timestamp=2024-08-28T12:23:23.682875Z module=smart_open_lib funcName=open taskName=Task-6
DEBUG Starting new HTTP connection (1): hb.bizmrg.com:80 | timestamp=2024-08-28T12:23:23.688591Z module=connectionpool funcName=_new_conn taskName=Task-6
[2024-08-28 15:23:42 +0300] [7] [CRITICAL] WORKER TIMEOUT (pid:9)
[2024-08-28 15:23:42 +0300] [7] [ERROR] Worker (pid:9) was sent SIGABRT!

**Comment by aminalaee** [comment]
I can’t still figure out what is going on here. Keeping this open for help.
